version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - vboxe-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/vboxe
      - SPRING_REDIS_HOST=redis
      - JWT_SECRET=javainuse
      - JWT_EXPIRATION_DATE_IN_MS=3600000
      - JWT_REFRESH_EXPIRATION_DATE_IN_MS=5400000
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-vboxe2022@gmail.com}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-your_app_password}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=2000MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=2000MB
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - vboxe-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - vboxe-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - vboxe-network

volumes:
  mongodb_data:
  redis_data:

networks:
  vboxe-network:
    driver: bridge
